version: '3.8'

services:
  # Serviciul 1: Serverul de Chat
  chat-server:
    build: .
    container_name: python_chat_server
    ports:
      - "${PORT:-5555}:5555"
    depends_on:
      - ollama # Așteaptă să pornească AI-ul
    environment:
      - OLLAMA_HOST=http://ollama:11434/v1
    restart: always

  # Serviciul 2: AI-ul Local (Ollama)
  ollama:
    image: ollama/ollama:latest
    container_name: ollama_backend
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: always

volumes:
  ollama_data: