version: '3.8' # Poti sterge aceasta linie sau o poti lasa

services:
  chat-server:
    build: .
    container_name: python_chat_server
    ports:
      - "${PORT:-5555}:5555"
    env_file:
      - .env
    restart: always